# Generated by Django 4.2.3 on 2023-09-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, verbose_name='Ürün İsmi')),
                ('aciklamasi', models.CharField(max_length=50, verbose_name='Ürün Açıklaması')),
                ('fiyat', models.IntegerField(verbose_name='Ürün Fiyatı')),
                ('urunResmi', models.ImageField(upload_to='', verbose_name='Ürün İsmi')),
            ],
        ),
    ]
