# Generated by Django 4.2.3 on 2023-09-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestorantApp', '0002_kategori_menu_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='kategori',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
