# Generated by Django 4.2.3 on 2023-09-23 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestorantApp', '0003_remove_menu_kategori_delete_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, verbose_name='Kategori Adı')),
                ('resim', models.ImageField(upload_to='', verbose_name='Kategori Resmi')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RestorantApp.kategori', verbose_name='Ürün Kategorisi'),
            preserve_default=False,
        ),
    ]
